server:
  # 统一 API 入口（与 block-snap-web/vite.config.js 代理目标一致）
  port: 80

spring:
  application:
    name: block-snap-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      # 全局跨域配置
      globalcors:
        add-to-simple-url-handler-mapping: true # 极其重要：解决 OPTIONS 预检请求被网关拦截导致跨域失败的问题
        cors-configurations:
          '[/**]': # 拦截所有请求路径
            allowedOriginPatterns: "*" # 允许所有的源头（前端所在域名/IP）。Spring Boot 2.4 之后强烈建议用 allowedOriginPatterns 代替 allowedOrigins
            allowedMethods: # 允许所有的 HTTP 方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*" # 允许所有的请求头（比如我们自定义的 Authorization, X-User-Id 等）
            allowCredentials: true # 允许前端携带 Cookie 等凭证
            maxAge: 3600 # 跨域允许的缓存时间（秒），避免浏览器每次都发 OPTIONS 请求探测

      routes:
        # 系统模块 block-snap-system :8081
        - id: system_route
          uri: lb://block-snap-system
          predicates:
            - Path=/sys-user/**

        # 业务模块 block-snap-service :8082（路径前缀与 Controller @RequestMapping 一致，不做 StripPrefix）
        - id: service_instance_route
          uri: lb://block-snap-service
          predicates:
            - Path=/svc-instance/**
        - id: service_snapshot_route
          uri: lb://block-snap-service
          predicates:
            - Path=/svc-snapshot/**
        - id: service_mod_route
          uri: lb://block-snap-service
          predicates:
            - Path=/svc-mod/**

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password:      # 如果有密码请填写
      database: 0
      lettuce:
        pool:
          max-active: 8 # 连接池配置