server:
  port: 8081

spring:
  application:
    name: block-snap-system # 须与网关 lb://block-snap-system 一致

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/block_snap_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      lettuce:
        pool:
          max-active: 8
