server:
  port: 8081 # 当前微服务的本地启动端口

spring:
  application:
    name: block-snap-system # 🚨 极其重要：这既是注册到 Nacos 的服务名，也是去 Nacos 找配置文件的核心凭证！

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

#  flyway:
#    # 是否启用 Flyway (默认 true)
#    enabled: true
#    # 迁移脚本的位置 (默认 classpath:db/migration)
#    locations:
#      - classpath:db/migration
#      - classpath:db/specific_vendor
#    # 针对不同数据库的编码 (默认 UTF-8)
#    encoding: UTF-8
#    # 迁移时是否允许无序执行 (开发环境建议 true，生产建议 false)
#    out-of-order: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/block_snap_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root     # 换成你 Docker 里 MySQL 的用户名
    password: root # 换成你 Docker 里 MySQL 的密码

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      lettuce:
        pool:
          max-active: 8

