server:
  port: 8082 # system 是 8081，所以业务模块顺延用 8082

spring:
  application:
    name: block-snap-service # 注册到 Nacos 的服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  # 数据库和 Redis 配置（可以直接从 system 模块复制过来）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/block_snap_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6380
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true